### ISSUE TITLE
is not exist a rule like genrules, that I can wrapper some project I don't to change it

### ISSUE THREAD

**Issue by wondfor** [just-buildsystem/justbuild#21]
like this:
`
genrule(
    name = "foo",
    srcs = [],
    outs = ["foo.h"],
    cmd = "./$(location create_foo.pl) > \"$@\"",
    tools = ["create_foo.pl"],
)
`

**Comment by oreiche** [comment]
Hi @wondfor,

yes, we do support generic targets. Please have a look at the documentation for the [built-in generic rule](https://github.com/just-buildsystem/justbuild/blob/502b016897a7561bcd0158f9f6120f56ba35cef9/doc/concepts/built-in-rules.org#generic). Furthermore, we also have rules for employing foreign build systems described in our [rules-cc repository](https://github.com/just-buildsystem/rules-cc#consume-and-being-consumed-by-cmake-libraries).

For the example you gave, an equivalent description in JustBuild would look like this:
~~~json
{ "foo":
  { "type": "generic"
  , "cmds": ["./create_foo.pl > foo.h"]
  , "outs": ["foo.h"]
  , "deps": ["create_foo.pl"]
  }
}
~~~
