### ISSUE TITLE
Bootstrapping against preinstalled dependencies fails with latest libgit2

### ISSUE THREAD

**Issue by oreiche** [just-buildsystem/justbuild#29]
While preparing for the `1.1.0` release of `JustBuild`, we were building and testing against `libgit2` with the (back-then up-to-date) version `1.5.2`. However, `libgit2` recently released version `1.6.4`, which seemed to introduce an issue:

Bootstrapping will fail due to `libgit2`'s `treebuilder` producing corrupted tree objects, causing errors when composing an action directory. We are unsure what exactly is causing this issue, but our current investigations strongly indicate that it might be related to a bug in `libgit2`.

This issue only occurs when building against `libgit2 >1.5.2`. If you want to [bootstrap against preinstalled dependencies](https://github.com/just-buildsystem/justbuild/blob/master/INSTALL.md#bootstrapping-against-preinstalled-dependencies-package-building) on a system that ships with an affected `libgit2` version, make sure to bootstrap with `NON_LOCAL_DEPS='["com_github_libgit2_libgit2"]'`. In this way, the bundled `libgit2` version `1.5.2` will be used.

**Comment by oreiche** [comment]
Related to issue https://github.com/libgit2/libgit2/issues/6553.

**Comment by oreiche** [comment]
The [fix](https://github.com/libgit2/libgit2/pull/6554) was merged and has been tagged with `v1.6`, so this issue should be solved with upcoming version `v1.6.5`.

**Comment by aehlig** [comment]
`libgit2` released [1.7.0](https://github.com/libgit2/libgit2/releases/tag/v1.7.0) containing the fix. We will update the used version of `libgit2` soon.

**Comment by aehlig** [comment]
Updated in 90ddcb1722c07aba3b92652fb407c4cae3c0cfa6
