### ISSUE TITLE
Distribute alternatives to .org files

### ISSUE THREAD

**Issue by Nicholas42** [just-buildsystem/justbuild#32]
It would be convenient to distribute the documentation/help files in other formats than .org. For one, github does not render them perfectly (in particular: ~"foo"~ ) and it is a typical use case to read them on git. Further, in an installation, it would be good to have them as man pages. The AUR package currently does this by requiring emacs as a make dependency, which is a bit excessive for those of us who do not use emacs.

I am unsure what the correct way to handle this, is. Having them checked-in in three formats is probably not that great. Maybe there is a format that can be converted to all formats by a program more lightweight than emacs.

**Comment by leahneukirchen** [comment]
+1 for prerendered man pages in release tarballs, from a distro maintainer POV.

**Comment by oreiche** [comment]
@leahneukirchen Would pandoc be an acceptable build dependency? I'm asking because pandoc can correctly generate man pages from markdown. In this case we would convert orgmode files to markdown and avoid committing generated man pages to the repository.

**Comment by leahneukirchen** [comment]
We use pandoc for other packages already, yes.

**Comment by oreiche** [comment]
@leahneukirchen thanks! We just released [version 1.1.1](https://github.com/just-buildsystem/justbuild/releases/tag/v1.1.1), which contains all man pages in markdown format.

@Nicholas42 We are currently in the process of converting all public documentation from orgmode files to markdown. This process should be finished soon.

**Comment by oreiche** [comment]
Most files have been converted to markdown with commit b66a7359fbbff35af630c88c56598bbc06b393e1.  
Thanks again for reporting!

Closing this issue.
