### ISSUE TITLE
Bootstrap fails on i686

### ISSUE THREAD

**Issue by leahneukirchen** [just-buildsystem/justbuild#33]
Perhaps this is out of scope for you, but also should be easy to fix:

A bootstrap on 32-bit Intel fails with:

```
Unpacking 'ssl' from '/builddir/justbuild-1.1.1/just-work/fetch/6195bf8242156c9a2fa75702eee058f91b86a88b.tar.gz'
Running ['sh', '-c', "SYS=`uname -s | tr 'A-Z' 'a-z'` && ARCH=`uname -m` && cc '-g' -I . -I src/include -c *.c src/crypto/*.c  src/crypto/*/*.c $SYS-$ARCH/crypto/fipsmodule/*.S && /usr/bin/ar cqs libcrypto.a *.o"] in '/builddir/justbuild-1.1.1/just-work/deps/ssl/boringssl-6195bf8242156c9a2fa75702eee058f91b86a88b'
cc1: fatal error: linux-i686/crypto/fipsmodule/*.S: No such file or directory
compilation terminated.
```

The correct directory name is `linux-x86/crypto/fipsmodule`.

**Comment by oreiche** [comment]
Hi @leahneukirchen, thank you for reporting this!

Our suggested solution would be https://github.com/just-buildsystem/justbuild/pull/34. Could you please confirm if this solves your issues for bootstrapping on i686?

**Comment by oreiche** [comment]
The fix has be merged. Thanks again!
