### ISSUE TITLE
Bootstrapping fails with clang 15.0.7 due to warning "array-parameter" in BoringSSL

### ISSUE THREAD

**Issue by mhthies** [just-buildsystem/justbuild#8]
I'm trying to bootstrap-build *justbuild* on ArchLinux using CLang 15.0.7. Unfortunately, the compilation fails due to a warning in BoringSSL, which is built with `-Werror` (even when configuring `"COMPILER_FAMILY": "unknown"`):

```txt
Running ['/usr/bin/clang', '-O2', '-DNDEBUG', '-std=gnu17', '-Wa,--noexecstack', '-D_XOPEN_SOURCE=700', '-Wall', '-Werror', '-Wformat=2', '-Wsign-compare', '-Wmissing-field-initializers', '-Wwrite-strings', '-Wshadow', '-fno-common', '-I', 'work', '-isystem', 'include', '-c', 'work/src/crypto/fipsmodule/bcm.c', '-o', 'work/src/crypto/fipsmodule/bcm.o'] with env {'PATH': '/bin:/sbin:/usr/bin:/usr/sbin'} for action 'dee9161ccc9d5793778e365f064834ab836dcc47'
In file included from work/src/crypto/fipsmodule/bcm.c:38:
work/src/crypto/fipsmodule/bn/asm/x86_64-gcc.c:427:51: error: argument 'a' of type 'const uint64_t[8]' (aka 'const unsigned long[8]') with mismatched bound [-Werror,-Warray-parameter]
void bn_sqr_comba8(BN_ULONG r[16], const BN_ULONG a[8]) {
                                                  ^
work/src/crypto/fipsmodule/bn/asm/../internal.h:292:51: note: previously declared as 'const uint64_t[4]' (aka 'const unsigned long[4]') here
void bn_sqr_comba8(BN_ULONG r[16], const BN_ULONG a[4]);
                                                  ^
```

I'm using the following command line:

```sh
env JUST_BUILD_CONF='{"COMPILER_FAMILY": "unknown", "CC": "/usr/bin/clang", "CXX": "/usr/bin/clang++", "AR": "/usr/bin/ar"}' python3 ./bin/bootstrap.py .
```

Output of `clang --version`:
```txt
clang version 15.0.7
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

As a workaround, I have removed the `-Werror` from the `posix_copts` array in `etc/defaults/CC/TARGETS.boringssl`.

**Comment by oreiche** [comment]
Thanks @mhthies, your workaround is actually a good solution. We will drop `-Werror` for externals, as it is not our job to lint external projects at all.

Would it be fine for you if we are putting you as a co-author for the upcoming change?

**Comment by mhthies** [comment]
> Would it be fine for you if we are putting you as a co-author for the upcoming change?

Of course, if you consider this to be justified. :)

**Comment by oreiche** [comment]
Sure, we really appreciate your efforts. :)

The change is in with commit https://github.com/just-buildsystem/justbuild/commit/31cb23a32d0665777a82799f3f476266882516cb. Closing this issue.
