### ISSUE TITLE
Boostrap: Allow selecting which of the dependencies are searched in local root

### ISSUE THREAD

**Issue by mhthies** [just-buildsystem/justbuild#9]
I'm trying to package *justbuild* for ArchLinux, linking against native shared libraries, provided by ArchLinux packages as far as possible. Thus, I use the bootstrap.py script with the environment variables `PACKAGE=YES LOCALBASE=/usr`.

However, some of the dependencies are not available from official ArchLinux packages yet:
- *gsl-lite* is only available from an Arch User Repository (AUR) package and only in a more (too) recent version
- *google_apis* and *bazel_remote_apis* are not packaged at all by now to my knowledge

Of course, I could create AUR packages for the two Google API repositories and work around the gsl-lite version mismatch. But, as all of these are quite small "compile-time" dependencies, I would like to let the bootstrap script fetch them, while still using Arch's pre-build shared libraries for all other dependencies. Thus, I'd like to be able to select which of the dependencies are downloaded as normal instead of being are searched in the local root directory, e.g. using an environment variable.

I already implemented this feature as a minimal patch for the `bootstrap.py` script, which simply skips some of the repositories in `config_to_local()` based on an environment variable (see [this commit](https://github.com/mhthies/justbuild/commit/0de35ad75aaaa99b5af2d9b2149ae4546db89c86)). This was sufficient in my case, but actually only works for header-only and protobuf dependencies, because the "import targets" repository is switched to "etc/import.prebuild" globally. Thus, it's not possible to use the *build* target definitions for selected dependencies this way.

**Comment by aehlig** [comment]
Thanks for your suggestion. I think it is a good idea to support such a mixed form of bootstrapping. I amended your commit to keep a backup copy of changed file layers, removing the restriction you mentioned that you patch only works for header-only libraries and similar constructs; I also changed the syntax for `NON_LOCAL_DEPS` to expect a json list, keeping it more in line with the other environment variables honored. I also added a test in a separate commit. Can you have a look at #16 and let me know what you think?

**Comment by aehlig** [comment]
Thank you for your comment. I've rebased the pull request and also amended the commit to have an additional comment, so that at least all the high-level steps in the transition to a local build with some non-local dependencies are documented.

**Comment by aehlig** [comment]
I believe this issue is fixed by 48115e5c803a2c73d35d047a9a0d9b2ea1352e64.
